### PR TITLE
Add if_has_service for iptables

### PR DESCRIPTION
**Pull request by PACordonnier**

### CODE REVIEW

**Comment by wdavidw** [comment]
Welcome @PACordonnier to the party, good catch

**Comment by leopaul36** [comment]
Thanks @PACordonnier :tada:

**Comment by lucasbak** [comment]
not sure the solution is right. Indeed Mariadb does not need iptables for working, but the rule is needed in case the iptables is activated on your host.
Now if iptables is not present you should have in the configuration actions to stop.
It the iptables service is installed by an external source, the rule will not be enabled because of @has_service('masson/core/iptables')
Open to discuss

**Comment by wdavidw** [comment]
@PACordonnier used the solution already present in some of our service (eg [openldap](https://github.com/adaltas/node-masson/blob/master/core/openldap_server/install.coffee.md). I agree with your argument, but if we wish to support such a scenario, it should be discussed in a separate thread and apply consistently accros masson and ryba services.

**Comment by lucasbak** [comment]
agreed

**Pull request merged**
