### PR TITLE
core/network: add host_replace option

### PR DESCRIPTION
**Pull request by leopaul36**

### CODE REVIEW

**Comment by wdavidw** [comment]
`host_replace` should re-introduce the old behavior and map to an object where keys are ip and values are string. When calling file, you should transform this object into an array:

```
@file
  key: value
  write: (
    match: RegExp "^#{quote ip}\\s.*$", 'm'
    replace: "#{ip} #{@config.host_replace[ip]}"
  ) for ip in Object.keys @config.host_replace
```

**Comment by leopaul36** [comment]
Sorry I misunderstood what you meant by "old behaviour".
Updated the PR, should be better now :+1:

**Comment by wdavidw** [comment]
could you also update the changelog and provide an exemple ?

**Comment by leopaul36** [comment]
Done :+1:

**Comment by IDerr** [comment]
I have fixed the changelog conflict, @leopaul36 I don't know if there's still changes to make here.

**Comment by wdavidw** [comment]
Thank you both

**Pull request merged**
